// Generated by TMBtools: do not edit by hand

#define TMB_LIB_INIT R_init_popMethods_TMBExports
#include <TMB.hpp>
#include "popReconstruct.hpp"

template<class Type>
Type objective_function<Type>::operator() () {
  DATA_STRING(model);
  if(model == "popReconstruct") {
    return popReconstruct(this);
  } else {
    error("Unknown model.");
  }
  return 0;
}
